# Polynomial Regression

In [1]:
import pandas as pd
data=pd.read_csv("Logisticdata.csv")

In [2]:
data

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
0,842,0,2.2,0,1,0,7,0.6,188,2,...,20,756,2549,9,7,19,0,0,1,1
1,1021,1,0.5,1,0,1,53,0.7,136,3,...,905,1988,2631,17,3,7,1,1,0,2
2,563,1,0.5,1,2,1,41,0.9,145,5,...,1263,1716,2603,11,2,9,1,1,0,2
3,615,1,2.5,0,0,0,10,0.8,131,6,...,1216,1786,2769,16,8,11,1,0,0,2
4,1821,1,1.2,0,13,1,44,0.6,141,2,...,1208,1212,1411,8,2,15,1,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,794,1,0.5,1,0,1,2,0.8,106,6,...,1222,1890,668,13,4,19,1,1,0,0
1996,1965,1,2.6,1,0,0,39,0.2,187,4,...,915,1965,2032,11,10,16,1,1,1,2
1997,1911,0,0.9,1,1,1,36,0.7,108,8,...,868,1632,3057,9,1,5,1,1,0,3
1998,1512,0,0.9,0,4,1,46,0.1,145,5,...,336,670,869,18,10,19,1,1,1,0
1999,510,1,2.0,1,5,1,45,0.9,168,6,...,483,754,3919,19,4,2,1,1,1,3

In [3]:
y=data["battery_power"]

In [4]:
x=data.iloc[:,1:]

In [5]:
x

,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,pc,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
0,0,2.2,0,1,0,7,0.6,188,2,2,20,756,2549,9,7,19,0,0,1,1
1,1,0.5,1,0,1,53,0.7,136,3,6,905,1988,2631,17,3,7,1,1,0,2
2,1,0.5,1,2,1,41,0.9,145,5,6,1263,1716,2603,11,2,9,1,1,0,2
3,1,2.5,0,0,0,10,0.8,131,6,9,1216,1786,2769,16,8,11,1,0,0,2
4,1,1.2,0,13,1,44,0.6,141,2,14,1208,1212,1411,8,2,15,1,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1,0.5,1,0,1,2,0.8,106,6,14,1222,1890,668,13,4,19,1,1,0,0
1996,1,2.6,1,0,0,39,0.2,187,4,3,915,1965,2032,11,10,16,1,1,1,2
1997,0,0.9,1,1,1,36,0.7,108,8,3,868,1632,3057,9,1,5,1,1,0,3
1998,0,0.9,0,4,1,46,0.1,145,5,5,336,670,869,18,10,19,1,1,1,0
1999,1,2.0,1,5,1,45,0.9,168,6,16,483,754,3919,19,4,2,1,1,1,3

In [6]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 1/3, random_state = 0)

In [7]:
from sklearn.linear_model import LinearRegression

In [8]:
model=LinearRegression()

In [9]:
model.fit(x_train,y_train)

LinearRegression()

In [10]:
model.coef_

array([-4.10481796e+00,  4.30656563e+00, -8.61823095e+00, -1.31272099e-01,
        7.57337045e+00, -7.51261904e-01,  4.75013511e+01,  5.55684380e-01,
        2.80046416e+00,  1.70582072e+00, -1.83049065e-01, -1.85543302e-01,
       -6.07699749e-01, -1.10199409e+00, -2.86249474e+00,  3.43199950e+00,
       -6.53350226e-01,  1.16211099e+01,  1.56691147e+01,  6.44574481e+02])

In [11]:
model.intercept_

1784.1245124262564

In [12]:
model.score(x_train,y_train)

0.3391823098050011

In [13]:
model.score(x_test,y_test)

0.3123935344682568

* Model is Underfit

In [14]:
x_train.shape

(1333, 20)

In [15]:
x_test.shape

(667, 20)

In [16]:
y_train.shape

(1333,)

In [17]:
y_test.shape

(667,)

# Predict the Given Data

In [18]:
x=[0,2.2,0,1,0,7,0.6,188,2,2,20,756,2549,9,7,19,0,0,1,1]
prediction = model.predict([x])
print(prediction)

[932.72869425]

C:\Users\Madhur Chauhan\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:441: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [19]:
y

0        842
1       1021
2        563
3        615
4       1821
        ...
1995     794
1996    1965
1997    1911
1998    1512
1999     510
Name: battery_power, Length: 2000, dtype: int64

* Actual Value = 842
* Prediction Value = 932.72869425